[package]
name = "smart_touhou_sorter"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.14.0"
jiff = { version = "0.2.16", features = ["serde"] }
ordered-float = "5.1.0"
rand = "0.9.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
smallvec = { version = "1.15.1", features = ["serde"] }

[dev-dependencies]
# Used in UTs since we need to explicitly seed an RNG so test results are reproducible
rand_chacha = "0.9.0"
