[package]
name = "engine"
version = "0.1.0"
edition = "2024"

[dependencies]
jiff = { workspace = true }
ordered-float = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
smallvec = { workspace = true }

[dev-dependencies]
rand_chacha = { workspace = true }
